//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveAhead
        {
            get
            {
                return SteamVR_Actions.default_MoveAhead;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuToggle
        {
            get
            {
                return SteamVR_Actions.default_MenuToggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.default_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBehind
        {
            get
            {
                return SteamVR_Actions.default_MoveBehind;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveLeft
        {
            get
            {
                return SteamVR_Actions.default_MoveLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveRight
        {
            get
            {
                return SteamVR_Actions.default_MoveRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
